version: '3.9'

services:
  app:
    image: hangoverhgv/portofolio:latest
    container_name: app
    ports:
      - 80:5000
    depends_on:
      - mariadb
    environment:
      MARIADB_DATABASE:
      MARIADB_USER:
      MARIADB_PASSWORD:
      MARIADB_HOST:

  mariadb:
    image: mariadb:10.8.3-jammy
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD:
      MARIADB_DATABASE:
      MARIADB_USER:
      MARIADB_PASSWORD: